apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-flask-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: practice-flask-app
  template:
    metadata:
      labels:
        app: practice-flask-app
    spec:
      containers:
      - name: practice-flask-app
        image: laviniak/practice-flask-app:latest
        ports:
        - containerPort: 80