- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      src: "service.yml"
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      src: "deployment.yml"