apiVersion: v1
kind: Service
metadata:
  name: practice-flask-app
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
  type: NodePort